### PR TITLE
update policy to work with vault v2

### PR DESCRIPTION
**Pull request by xiujiao**

### CODE REVIEW

**Comment by xiujiao** [comment]
> Are there other paths? like `secret/metadata/exodus/*` that need fixin?

It was not needed for the issue I had, but it is a good catch. I pushed the change to include the metadata part in the policy

**Comment by thomasmitchell** [comment]
POST to secret/metadata/exodus/... is technically legal, even though I don't think its used in safe. Still, you may want to include update for the metadata endpoint policy.

**Comment by xiujiao** [comment]
> POST to secret/metadata/exodus/... is technically legal, even though I don't think its used in safe. Still, you may want to include update for the metadata endpoint policy.

Added

**Comment by xiujiao** [comment]
Could you @thomasmitchell merge it if ILGY?

**Pull request merged**
