### PR TITLE
bump haproxy to 8.4.2

### PR DESCRIPTION
**Pull request by xiujiao**

### CODE REVIEW

**Comment by xiujiao** [comment]
It deployed successfully, but did not work. Do not merge yet

**Comment by thomasmmitchell** [comment]
What about it did not work?

**Comment by xiujiao** [comment]
@thomasmmitchell It is working. You can merge it now. It was I did not know that sslip.io is not supported anymore.

**Comment by xiujiao** [comment]
Could someone merge this PR? FYI: do not use the sha1 from bosh.io, it does not match the release. uses the sha1 in the releases repo itself

**Comment by thomasmmitchell** [comment]
Can you please switch it to use the bosh.io release entirely for consistency with other kits and past releases?

**Pull request merged**
